import fs from 'fs';
import path from 'path';

/**
 * @typedef {{ thumb: string, full: string }} GalleryImage
 */

/**
 * Read gallery images from a folder under static/images/irl/.
 * Runs at build time during prerendering to bake the image list into static output.
 *
 * Each image is paired with its ribbon thumbnail from static/images/irl-thumbs/
 * (generated by scripts/generate-thumbnails.mjs via the prebuild/predev hooks).
 * If a thumbnail is missing, the original is used for both.
 *
 * @param {string} folder - Subfolder name (e.g. 'east', 'north', 'mpls')
 * @returns {GalleryImage[]} Array of thumb/full URL path pairs
 */
export function getGalleryImages(folder) {
	if (!folder) return [];

	const dir = path.join(process.cwd(), 'static', 'images', 'irl', folder);
	const thumbDir = path.join(process.cwd(), 'static', 'images', 'irl-thumbs', folder);

	if (!fs.existsSync(dir)) return [];

	return fs
		.readdirSync(dir)
		.filter((f) => /\.(jpg|jpeg|png|webp)$/i.test(f))
		.sort((a, b) => a.localeCompare(b))
		.map((f) => {
			const full = `/images/irl/${folder}/${f}`;
			const thumbName = f.replace(/\.(jpg|jpeg|png|webp)$/i, '') + '.webp';
			const thumb = fs.existsSync(path.join(thumbDir, thumbName))
				? `/images/irl-thumbs/${folder}/${thumbName}`
				: full;
			return { thumb, full };
		});
}

/**
 * Get the first image from each gallery folder that has images.
 * Used on the homepage to build a sampler ribbon.
 *
 * @param {string[]} folders - Array of subfolder names
 * @returns {GalleryImage[]} Array of thumb/full pairs (one per folder that has images)
 */
export function getFirstImagePerFolder(folders) {
	/** @type {GalleryImage[]} */
	const result = [];

	for (const folder of folders) {
		const images = getGalleryImages(folder);
		if (images.length > 0) {
			result.push(images[0]);
		}
	}

	return result;
}
